project:
  type: website

website:
  title: "gis-portfolio-max-larner"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: assignment1/assignment1.qmd
        text: "Project 1: Shortest Border"
      - href: assignment2/assignment2.qmd
        text: "Project 2: Weighted Redistribution"
      - href: about.qmd
        text: About Me

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


