---
title: _
format:
  html:
    toc: false
    page-layout: full
---

<div class="hero">
  <h1>Geospatial projects & conservation analysis</h1>
  <p>A portfolio of recent GIS projects and Dissertation</p>
  <div class="actions">
  [View Projects](/projects/project_list.qmd){.btn}
  [About Me](/about.qmd){.btn}
  </div>
</div>

## Featured Projects {.section}

<div class="container">
<div class="projects-grid">

::: {.project-card}
### Dissertation Project – Spatial optimisation
<p class="text-soft">Optimising reserve selection under pine marten recolonisation in Cumbria.</p>
<a class="btn" href="projects/dissertation/dissertation.qmd">Open</a>
:::

::: {.project-card}
### World’s Shortest Border Algorithm
<p class="text-soft">Finding the shortest land border via spatial indexing & geodesic geometry.</p>
<a class="btn" href="projects/assignment1/assignment1.qmd">Open</a>
:::

::: {.project-card}
### Spatial Redistribution Algorithm
<p class="text-soft">Implementing Jonny Huck’s 2014 algorithm to redistribute ambiguous points.</p>
<a class="btn" href="projects/assignment2/assignment2.qmd">Open</a>
:::

</div>
</div>

## About Me {.section}

I’m a 1st‑class Geography BSc graduate from the University of Manchester, looking for opportunities in GIS‑informed consultation, or technical roles.  My interests span planning, landscape ecology/BNG, and sustainable development - opportunities aligned with these goals are always welcome.

You can see all my code on [GitHub](https://github.com/MaxLarner/gis-portfolio-max-larner) or reach me via [LinkedIn](https://linkedin.com/in/max-larner-b53610208) or email at max.larner123@gmail.com.